name: CI Benchmark (No Cache)

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.14'
  FLAKY_TESTS: keep_retrying
  CLANG_VERSION: '19'
  CC: clang-19
  CXX: clang++-19
  SCCACHE_GHA_ENABLED: 'false'
  RUSTC_VERSION: '1.82'

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - monkci-ubuntu-24.04-4-3600iops
          - ubuntu-latest
        include:
          - python-version: "3.10"
            debian-version: trixie
          - python-version: "3.12"
            debian-version: trixie
          - python-version: "3.13"
            debian-version: trixie
          - python-version: "3.14"
            debian-version: trixie
    container:
      image: python:${{ matrix.python-version }}-${{ matrix.debian-version }}
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends gettext make
      - name: Install nox
        run: pip install nox
      - name: Run tests
        run: nox -x --session "test-${{ matrix.python-version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - monkci-ubuntu-24.04-4-3600iops
          - ubuntu-latest
        python-version: ["3.14"]
    container:
      image: python:3.14-trixie
    steps:
      - uses: actions/checkout@v6
      - name: Install nox
        run: pip install nox
      - name: Build docs
        run: nox -x --session "docs"

  lint:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - monkci-ubuntu-24.04-4-3600iops
          - ubuntu-latest
        python-version: ["3.14"]
    container:
      image: python:3.14-trixie
    steps:
      - uses: actions/checkout@v6
      - name: Install nox
        run: pip install nox
      - name: Run linter
        run: nox -x -t lint

  standardjs:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - monkci-ubuntu-24.04-4-3600iops
          - ubuntu-latest
        python-version: ["3.14"]
    container:
      image: node:22-trixie
    steps:
      - uses: actions/checkout@v6
      - name: Install standardjs dependencies
        run: make ci-install-standardjs
      - name: Run standardjs
        run: make standardjs
